// seeders/menuSeeder.js
const MasterMenu = require("../model/masterData/menu/masterMenuModel");

const menuData = [
  {
    name: "Dashboard",
    icon: "Dashboard",
    path: null,
    level: 1,
    order_index: 1,
    children: [
      {
        name: "Main Dashboard",
        icon: "dashboard",
        path: "/dashboard",
        level: 2,
        order_index: 1,
      },
      {
        name: "Maintenance Dashboard",
        icon: "dashboard",
        path: "/dashboard/maintenance",
        level: 2,
        order_index: 2,
      },
    ],
  },
  {
    name: "Maintenance",
    icon: "MaintenanceIcon",
    path: null,
    level: 1,
    order_index: 2,
    children: [
      {
        name: "Corrective (CM)",
        icon: "machine",
        path: "/maintenance/corrective",
        level: 2,
        order_index: 1,
      },
      {
        name: "Preventive Maintenance (PM)",
        icon: "preventive",
        path: null,
        level: 2,
        order_index: 2,
        children: [
          {
            name: "PM1",
            icon: "preventive",
            path: "/maintenance/preventive/pm1",
            level: 3,
            order_index: 1,
          },
          {
            name: "PM2",
            icon: "preventive",
            path: "/maintenance/preventive/pm2",
            level: 3,
            order_index: 2,
          },
          {
            name: "PM3",
            icon: "preventive",
            path: "/maintenance/preventive/pm3",
            level: 3,
            order_index: 3,
          },
          {
            name: "OS3",
            icon: "preventive",
            path: "/maintenance/preventive/os3",
            level: 3,
            order_index: 4,
          },
          {
            name: "History",
            icon: "history",
            path: "/maintenance/preventive/history",
            level: 3,
            order_index: 5,
          },
        ],
      },
      {
        name: "Outstanding",
        icon: "outstanding",
        path: "/maintenance/outstanding",
        level: 2,
        order_index: 3,
      },
      {
        name: "Absensi",
        icon: "attendance",
        path: "/maintenance/absensi",
        level: 2,
        order_index: 4,
      },
      {
        name: "Sparepart",
        icon: "sparepart",
        path: null,
        level: 2,
        order_index: 5,
        children: [
          {
            name: "Opname Adjustment",
            icon: "adjustment",
            path: "/maintenance/sparepart/opname/adjustment",
            level: 3,
            order_index: 1,
          },
          {
            name: "Stock Master",
            icon: "stock",
            path: "/maintenance/sparepart/stock-master",
            level: 3,
            order_index: 2,
          },
          {
            name: "Monitoring Sparepart",
            icon: "monitoring",
            path: "/maintenance/sparepart/monitoring",
            level: 3,
            order_index: 3,
          },
          {
            name: "Monitoring Service",
            icon: "monitoring",
            path: "/maintenance/sparepart/monitoring-service",
            level: 3,
            order_index: 4,
          },
        ],
      },
      {
        name: "Project",
        icon: "project",
        path: "/maintenance/project",
        level: 2,
        order_index: 6,
      },
      {
        name: "Recap",
        icon: "recap",
        path: "/maintenance/recap",
        level: 2,
        order_index: 7,
      },
      {
        name: "KPI",
        icon: "kpi",
        path: null,
        level: 2,
        order_index: 8,
        children: [
          {
            name: "Dashboard",
            icon: "dashboard",
            path: "/maintenance/kpi",
            level: 3,
            order_index: 1,
          },
          {
            name: "Form",
            icon: "form",
            path: "/maintenance/kpi/form",
            level: 3,
            order_index: 2,
          },
          {
            name: "Input",
            icon: "input",
            path: "/maintenance/kpi/input",
            level: 3,
            order_index: 3,
          },
        ],
      },
      {
        name: "Report",
        icon: "ncr",
        path: null,
        level: 2,
        order_index: 9,
        children: [
          {
            name: "NCR",
            icon: "ncr",
            path: "/maintenance/report/ncr",
            level: 3,
            order_index: 1,
          },
          {
            name: "CAPA",
            icon: "capa",
            path: "/maintenance/report/capa",
            level: 3,
            order_index: 2,
          },
        ],
      },
      {
        name: "SPB",
        icon: "service",
        path: "/maintenance/spb",
        level: 2,
        order_index: 10,
      },
      {
        name: "Submission to HR",
        icon: "document",
        path: null,
        level: 2,
        order_index: 11,
        children: [
          {
            name: "Submission",
            icon: "submission",
            path: "/maintenance/submission",
            level: 3,
            order_index: 1,
          },
          {
            name: "Submission History",
            icon: "history",
            path: "/maintenance/submission/history",
            level: 3,
            order_index: 2,
          },
          {
            name: "Position Submission",
            icon: "submission",
            path: "/maintenance/submission/position",
            level: 3,
            order_index: 3,
          },
          {
            name: "Position History",
            icon: "history",
            path: "/maintenance/submission/position/history",
            level: 3,
            order_index: 4,
          },
        ],
      },
    ],
  },
  {
    name: "Quality Control",
    icon: "QC",
    path: null,
    level: 1,
    order_index: 3,
    children: [
      {
        name: "Validate & Verify",
        icon: "validation",
        path: "/qc/validate-verify",
        level: 2,
        order_index: 1,
      },
      {
        name: "Quality Inspection",
        icon: "inspection",
        path: "/qc/inspection",
        level: 2,
        order_index: 2,
      },
      {
        name: "Kalibrasi Alat Ukur",
        icon: "calibration",
        path: "/qc/kalibrasi",
        level: 2,
        order_index: 3,
      },
      {
        name: "Kabag Approval",
        icon: "approval",
        path: "/qc/kabag-approval",
        level: 2,
        order_index: 4,
      },
      {
        name: "Outstanding",
        icon: "outstanding",
        path: "/qc/outstanding",
        level: 2,
        order_index: 5,
      },
      {
        name: "Recap",
        icon: "recap",
        path: "/qc/recap",
        level: 2,
        order_index: 6,
      },
      {
        name: "QMS",
        icon: "qms",
        path: null,
        level: 2,
        order_index: 7,
        children: [
          {
            name: "NCR",
            icon: "ncr",
            path: "/qc/qms/ncr",
            level: 3,
            order_index: 1,
          },
          {
            name: "CAPA",
            icon: "capa",
            path: "/qc/qms/capa",
            level: 3,
            order_index: 2,
          },
        ],
      },
      {
        name: "Report",
        icon: "report",
        path: null,
        level: 2,
        order_index: 8,
        children: [
          {
            name: "NCR",
            icon: "ncr",
            path: "/qc/report/ncr",
            level: 3,
            order_index: 1,
          },
          {
            name: "CAPA",
            icon: "capa",
            path: "/qc/report/capa",
            level: 3,
            order_index: 2,
          },
        ],
      },
      {
        name: "Absensi",
        icon: "attendance",
        path: "/qc/absensi",
        level: 2,
        order_index: 9,
      },
      {
        name: "Submission to HR",
        icon: "document",
        path: null,
        level: 2,
        order_index: 10,
        children: [
          {
            name: "Submission",
            icon: "submission",
            path: "/qc/submission",
            level: 3,
            order_index: 1,
          },
          {
            name: "Submission History",
            icon: "history",
            path: "/qc/submission/history",
            level: 3,
            order_index: 2,
          },
          {
            name: "Position Submission",
            icon: "submission",
            path: "/qc/submission/position",
            level: 3,
            order_index: 3,
          },
          {
            name: "Position History",
            icon: "history",
            path: "/qc/submission/position/history",
            level: 3,
            order_index: 4,
          },
        ],
      },
    ],
  },
  {
    name: "MR",
    icon: "QC",
    path: null,
    level: 1,
    order_index: 4,
    children: [
      {
        name: "QMS",
        icon: "qms",
        path: null,
        level: 2,
        order_index: 1,
        children: [
          {
            name: "NCR",
            icon: "ncr",
            path: "/mr/qms/ncr",
            level: 3,
            order_index: 1,
          },
          {
            name: "CAPA",
            icon: "capa",
            path: "/mr/qms/capa",
            level: 3,
            order_index: 2,
          },
        ],
      },
      {
        name: "Report",
        icon: "report",
        path: null,
        level: 2,
        order_index: 2,
        children: [
          {
            name: "NCR",
            icon: "ncr",
            path: "/mr/report/ncr",
            level: 3,
            order_index: 1,
          },
          {
            name: "CAPA",
            icon: "capa",
            path: "/mr/report/capa",
            level: 3,
            order_index: 2,
          },
        ],
      },
    ],
  },
  {
    name: "Human Resources",
    icon: "HRIcon",
    path: null,
    level: 1,
    order_index: 5,
    children: [
      {
        name: "Personnel Management",
        icon: "personnel",
        path: null,
        level: 2,
        order_index: 1,
        children: [
          {
            name: "Company",
            icon: "company",
            path: "/hr/personnel/company",
            level: 3,
            order_index: 1,
          },
          {
            name: "Employee",
            icon: "employee",
            path: "/hr/personnel/employee",
            level: 3,
            order_index: 2,
          },
          {
            name: "Work Calendar",
            icon: "calendar",
            path: "/hr/personnel/work-calendar",
            level: 3,
            order_index: 3,
          },
          {
            name: "Absensi",
            icon: "attendance",
            path: "/hr/personnel/absensi",
            level: 3,
            order_index: 4,
          },
        ],
      },
      {
        name: "Payroll",
        icon: "payroll",
        path: null,
        level: 2,
        order_index: 2,
        children: [
          {
            name: "Payroll",
            icon: "payroll",
            path: "/hr/payroll",
            level: 3,
            order_index: 1,
          },
          {
            name: "Monthly Payroll",
            icon: "payroll",
            path: "/hr/payroll/monthly",
            level: 3,
            order_index: 2,
          },
          {
            name: "Approval",
            icon: "approval",
            path: "/hr/payroll/approval",
            level: 3,
            order_index: 3,
          },
        ],
      },
      {
        name: "Submission",
        icon: "submission",
        path: null,
        level: 2,
        order_index: 3,
        children: [
          {
            name: "Submission",
            icon: "submission",
            path: "/hr/submission",
            level: 3,
            order_index: 1,
          },
          {
            name: "Submission History",
            icon: "history",
            path: "/hr/submission/history",
            level: 3,
            order_index: 2,
          },
          {
            name: "Position Submission",
            icon: "position",
            path: "/hr/submission/position",
            level: 3,
            order_index: 3,
          },
          {
            name: "Position History",
            icon: "history",
            path: "/hr/submission/position/history",
            level: 3,
            order_index: 4,
          },
        ],
      },
      {
        name: "Response",
        icon: "response",
        path: null,
        level: 2,
        order_index: 4,
        children: [
          {
            name: "Response",
            icon: "response",
            path: "/hr/response",
            level: 3,
            order_index: 1,
          },
          {
            name: "Response History",
            icon: "history",
            path: "/hr/response/history",
            level: 3,
            order_index: 2,
          },
          {
            name: "Position Response",
            icon: "position",
            path: "/hr/response/position",
            level: 3,
            order_index: 3,
          },
          {
            name: "Position History",
            icon: "history",
            path: "/hr/response/position/history",
            level: 3,
            order_index: 4,
          },
        ],
      },
      {
        name: "Recap",
        icon: "recap",
        path: "/hr/recap",
        level: 2,
        order_index: 5,
      },
      {
        name: "Outstanding",
        icon: "outstanding",
        path: "/hr/outstanding",
        level: 2,
        order_index: 6,
      },
      {
        name: "Report",
        icon: "report",
        path: null,
        level: 2,
        order_index: 7,
        children: [
          {
            name: "NCR",
            icon: "ncr",
            path: "/hr/report/ncr",
            level: 3,
            order_index: 1,
          },
          {
            name: "CAPA",
            icon: "capa",
            path: "/hr/report/capa",
            level: 3,
            order_index: 2,
          },
        ],
      },
    ],
  },
  {
    name: "PPIC",
    icon: "PPICIcon",
    path: null,
    level: 1,
    order_index: 6,
    children: [
      {
        name: "Production Schedule",
        icon: "schedule",
        path: "/ppic/production-schedule",
        level: 2,
        order_index: 1,
      },
      {
        name: "Scheduled JO",
        icon: "schedule",
        path: "/ppic/scheduled-jo",
        level: 2,
        order_index: 2,
      },
      {
        name: "Delivery Schedule",
        icon: "schedule",
        path: "/ppic/delivery-schedule",
        level: 2,
        order_index: 3,
      },
      {
        name: "Outstanding",
        icon: "outstanding",
        path: "/ppic/outstanding",
        level: 2,
        order_index: 4,
      },
      {
        name: "Recap",
        icon: "recap",
        path: "/ppic/recap",
        level: 2,
        order_index: 5,
      },
      {
        name: "BOM",
        icon: "bom",
        path: null,
        level: 2,
        order_index: 6,
        children: [
          {
            name: "Create BOM",
            icon: "create",
            path: "/ppic/bom/create",
            level: 3,
            order_index: 1,
          },
          {
            name: "Approval",
            icon: "approval",
            path: "/ppic/bom/approval",
            level: 3,
            order_index: 2,
          },
        ],
      },
      {
        name: "BOM PPIC",
        icon: "bom",
        path: null,
        level: 2,
        order_index: 7,
        children: [
          {
            name: "Create BOM PPIC",
            icon: "create",
            path: "/ppic/bom-ppic/create",
            level: 3,
            order_index: 1,
          },
        ],
      },
      {
        name: "JO",
        icon: "jo",
        path: null,
        level: 2,
        order_index: 8,
        children: [
          {
            name: "Create JO",
            icon: "create",
            path: "/ppic/jo/create",
            level: 3,
            order_index: 1,
          },
          {
            name: "Approval",
            icon: "approval",
            path: "/ppic/jo/approval",
            level: 3,
            order_index: 2,
          },
          {
            name: "History",
            icon: "history",
            path: "/ppic/jo/history",
            level: 3,
            order_index: 3,
          },
        ],
      },
      {
        name: "Submission to HR",
        icon: "document",
        path: null,
        level: 2,
        order_index: 9,
        children: [
          {
            name: "Submission",
            icon: "submission",
            path: "/ppic/submission",
            level: 3,
            order_index: 1,
          },
          {
            name: "Submission History",
            icon: "history",
            path: "/ppic/submission/history",
            level: 3,
            order_index: 2,
          },
          {
            name: "Position Submission",
            icon: "submission",
            path: "/ppic/submission/position",
            level: 3,
            order_index: 3,
          },
          {
            name: "Position History",
            icon: "history",
            path: "/ppic/submission/position/history",
            level: 3,
            order_index: 4,
          },
        ],
      },
    ],
  },
  {
    name: "Production",
    icon: "ProductionIcon",
    path: null,
    level: 1,
    order_index: 7,
    children: [
      {
        name: "Input LKH",
        icon: "input",
        path: "/production/input-lkh",
        level: 2,
        order_index: 1,
      },
      {
        name: "Monitoring LKH",
        icon: "input",
        path: "/production/monitoring-lkh",
        level: 2,
        order_index: 2,
      },
      {
        name: "Approve LKH",
        icon: "input",
        path: "/production/approve-lkh",
        level: 2,
        order_index: 3,
      },
      {
        name: "All Data LKH",
        icon: "input",
        path: "/production/alldata-lkh",
        level: 2,
        order_index: 4,
      },
      {
        name: "Buka LKH",
        icon: "input",
        path: "/production/buka-lkh",
        level: 2,
        order_index: 5,
      },
      {
        name: "List JO Selesai",
        icon: "input",
        path: "/production/list-jo-selesai",
        level: 2,
        order_index: 6,
      },
      {
        name: "Breakdown Recap",
        icon: "breakdown",
        path: "/production/breakdown-recap",
        level: 2,
        order_index: 7,
      },
      {
        name: "Waste Report",
        icon: "waste",
        path: "/production/waste-report",
        level: 2,
        order_index: 8,
      },
      {
        name: "OS2",
        icon: "machine",
        path: "/production/os2",
        level: 2,
        order_index: 9,
      },
      {
        name: "Absensi",
        icon: "attendance",
        path: "/production/absensi",
        level: 2,
        order_index: 10,
      },
      {
        name: "Submission to HR",
        icon: "document",
        path: null,
        level: 2,
        order_index: 11,
        children: [
          {
            name: "Submission",
            icon: "submission",
            path: "/production/submission",
            level: 3,
            order_index: 1,
          },
          {
            name: "Submission History",
            icon: "history",
            path: "/production/submission/history",
            level: 3,
            order_index: 2,
          },
          {
            name: "Position Submission",
            icon: "submission",
            path: "/production/submission/position",
            level: 3,
            order_index: 3,
          },
          {
            name: "Position History",
            icon: "history",
            path: "/production/submission/position/history",
            level: 3,
            order_index: 4,
          },
        ],
      },
    ],
  },
  {
    name: "Marketing",
    icon: "ProductionIcon",
    path: null,
    level: 1,
    order_index: 8,
    children: [
      {
        name: "Calculation",
        icon: "calculation",
        path: null,
        level: 2,
        order_index: 1,
        children: [
          {
            name: "Create",
            icon: "create",
            path: "/marketing/calculation/create",
            level: 3,
            order_index: 1,
          },
          {
            name: "History",
            icon: "history",
            path: "/marketing/calculation/history",
            level: 3,
            order_index: 2,
          },
        ],
      },
      {
        name: "Kabag Approval",
        icon: "approval",
        path: null,
        level: 2,
        order_index: 2,
        children: [
          {
            name: "Approval",
            icon: "approval",
            path: "/marketing/kabag-approval/list",
            level: 3,
            order_index: 1,
          },
          {
            name: "History",
            icon: "history",
            path: "/marketing/kabag-approval/history",
            level: 3,
            order_index: 2,
          },
        ],
      },
      {
        name: "OKP",
        icon: "okp",
        path: null,
        level: 2,
        order_index: 3,
        children: [
          {
            name: "Create",
            icon: "create",
            path: "/marketing/okp/create",
            level: 3,
            order_index: 1,
          },
          {
            name: "History",
            icon: "history",
            path: "/marketing/okp/history",
            level: 3,
            order_index: 2,
          },
        ],
      },
      {
        name: "IO",
        icon: "io",
        path: null,
        level: 2,
        order_index: 4,
        children: [
          {
            name: "Create",
            icon: "create",
            path: "/marketing/io/create",
            level: 3,
            order_index: 1,
          },
          {
            name: "NPD",
            icon: "npd",
            path: "/marketing/io/npd",
            level: 3,
            order_index: 2,
          },
          {
            name: "History",
            icon: "history",
            path: "/marketing/io/history",
            level: 3,
            order_index: 3,
          },
        ],
      },
      {
        name: "SO",
        icon: "so",
        path: null,
        level: 2,
        order_index: 5,
        children: [
          {
            name: "Create",
            icon: "create",
            path: "/marketing/so/create",
            level: 3,
            order_index: 1,
          },
          {
            name: "History",
            icon: "history",
            path: "/marketing/so/history",
            level: 3,
            order_index: 2,
          },
        ],
      },
      {
        name: "Perubahan Invoice",
        icon: "so",
        path: null,
        level: 2,
        order_index: 6,
        children: [
          {
            name: "Create",
            icon: "create",
            path: "/marketing/perubahan/create-perubahan",
            level: 3,
            order_index: 1,
          },
          {
            name: "List",
            icon: "list",
            path: "/marketing/perubahan/list-perubahan",
            level: 3,
            order_index: 2,
          },
          {
            name: "History",
            icon: "history",
            path: "/marketing/perubahan/history-perubahan",
            level: 3,
            order_index: 3,
          },
        ],
      },
    ],
  },
  {
    name: "Pre-Press",
    icon: "ProductionIcon",
    path: null,
    level: 1,
    order_index: 9,
    children: [
      {
        name: "Pre Press",
        icon: "prepress",
        path: "/prepress",
        level: 2,
        order_index: 1,
      },
    ],
  },
  {
    name: "Desain",
    icon: "ProductionIcon",
    path: null,
    level: 1,
    order_index: 10,
    children: [
      {
        name: "Desain",
        icon: "design",
        path: "/desain",
        level: 2,
        order_index: 1,
      },
    ],
  },
  {
    name: "Delivery Order",
    icon: "QC",
    path: null,
    level: 1,
    order_index: 11,
    children: [
      {
        name: "List DO",
        icon: "capa",
        path: "/do/list-do",
        level: 2,
        order_index: 1,
      },
      {
        name: "Konfirmasi DO",
        icon: "design",
        path: "/do/konfirmasi-do",
        level: 2,
        order_index: 2,
      },
    ],
  },
  {
    name: "Accounting",
    icon: "QC",
    path: null,
    level: 1,
    order_index: 12,
    children: [
      {
        name: "List Outstanding",
        icon: "deposit",
        path: "/accounting/list-outstanding",
        level: 2,
        order_index: 1,
      },
      {
        name: "List Request Invoice",
        icon: "deposit",
        path: "/accounting/list-request-invoice",
        level: 2,
        order_index: 2,
      },
      {
        name: "List Approve Invoice",
        icon: "deposit",
        path: "/accounting/list-approval-invoice",
        level: 2,
        order_index: 3,
      },
      {
        name: "List Approve Perubahan",
        icon: "deposit",
        path: "/accounting/list-approval-perubahan",
        level: 2,
        order_index: 4,
      },
      {
        name: "List All Invoice",
        icon: "deposit",
        path: "/accounting/list-invoice",
        level: 2,
        order_index: 5,
      },
      {
        name: "List Retur",
        icon: "deposit",
        path: "/accounting/list-retur",
        level: 2,
        order_index: 6,
      },
      {
        name: "Deposit",
        icon: "deposit",
        path: "/accounting/deposit",
        level: 2,
        order_index: 7,
      },
      {
        name: "Approval",
        icon: "approval",
        path: null,
        level: 2,
        order_index: 8,
        children: [
          {
            name: "Approval Deposit",
            icon: "approval",
            path: "/accounting/approval/deposit",
            level: 3,
            order_index: 1,
          },
          {
            name: "History Approval Deposit",
            icon: "history",
            path: "/accounting/approval/deposit-history",
            level: 3,
            order_index: 2,
          },
        ],
      },
    ],
  },
  {
    name: "Master Data",
    icon: "MasterDataIcon",
    path: null,
    level: 1,
    order_index: 13,
    children: [
      {
        name: "Maintenance",
        icon: "maintenance",
        path: null,
        level: 2,
        order_index: 1,
        children: [
          {
            name: "Machine",
            icon: "machine",
            path: "/master/maintenance/machine",
            level: 3,
            order_index: 1,
          },
          {
            name: "User",
            icon: "user",
            path: "/master/maintenance/user",
            level: 3,
            order_index: 2,
          },
          {
            name: "Role",
            icon: "role",
            path: "/master/maintenance/role",
            level: 3,
            order_index: 3,
          },
          {
            name: "Sparepart",
            icon: "sparepart",
            path: "/master/maintenance/sparepart",
            level: 3,
            order_index: 4,
          },
          {
            name: "Analysis",
            icon: "analysis",
            path: "/master/maintenance/analysis",
            level: 3,
            order_index: 5,
          },
          {
            name: "Monitoring",
            icon: "monitoring",
            path: "/master/maintenance/monitoring",
            level: 3,
            order_index: 6,
          },
          {
            name: "PM1",
            icon: "pm",
            path: "/master/maintenance/pm1",
            level: 3,
            order_index: 7,
          },
          {
            name: "PM2",
            icon: "pm",
            path: "/master/maintenance/pm2",
            level: 3,
            order_index: 8,
          },
          {
            name: "PM3",
            icon: "pm",
            path: "/master/maintenance/pm3",
            level: 3,
            order_index: 9,
          },
          {
            name: "KPI",
            icon: "kpi",
            path: "/master/maintenance/kpi",
            level: 3,
            order_index: 10,
          },
          {
            name: "Grade",
            icon: "grade",
            path: "/master/maintenance/grade",
            level: 3,
            order_index: 11,
          },
          {
            name: "Skor MTC",
            icon: "grade",
            path: "/master/maintenance/skor-mtc",
            level: 3,
            order_index: 12,
          },
        ],
      },
      {
        name: "Quality Control",
        icon: "qc",
        path: null,
        level: 2,
        order_index: 2,
        children: [
          {
            name: "Defect",
            icon: "defect",
            path: "/master/qc/defect",
            level: 3,
            order_index: 1,
          },
          {
            name: "Document",
            icon: "document",
            path: "/master/qc/document",
            level: 3,
            order_index: 2,
          },
          {
            name: "Final Inspection",
            icon: "inspection",
            path: "/master/qc/final-inspection",
            level: 3,
            order_index: 3,
          },
          {
            name: "User",
            icon: "user",
            path: "/master/qc/user",
            level: 3,
            order_index: 4,
          },
          {
            name: "Outsourcing BJ",
            icon: "outsourcing",
            path: "/master/qc/outsourcing-bj",
            level: 3,
            order_index: 5,
          },
          {
            name: "Kalibrasi",
            icon: "calibration",
            path: "/master/qc/kalibrasi",
            level: 3,
            order_index: 6,
          },
        ],
      },
      {
        name: "Human Resources",
        icon: "hr",
        path: null,
        level: 2,
        order_index: 3,
        children: [
          {
            name: "Shift",
            icon: "shift",
            path: "/master/hr/shift",
            level: 3,
            order_index: 1,
          },
          {
            name: "SP & Teguran",
            icon: "warning",
            path: "/master/hr/sp-teguran",
            level: 3,
            order_index: 2,
          },
          {
            name: "Setting",
            icon: "setting",
            path: "/master/hr/setting",
            level: 3,
            order_index: 3,
          },
          {
            name: "User",
            icon: "user",
            path: "/master/hr/user",
            level: 3,
            order_index: 4,
          },
          {
            name: "Kendaraan",
            icon: "vehicle",
            path: "/master/hr/kendaraan",
            level: 3,
            order_index: 5,
          },
          {
            name: "Department",
            icon: "department",
            path: "/master/hr/department",
            level: 3,
            order_index: 6,
          },
          {
            name: "Cuti Khusus",
            icon: "leave",
            path: "/master/hr/cuti-khusus",
            level: 3,
            order_index: 7,
          },
          {
            name: "Grade",
            icon: "grade",
            path: "/master/hr/grade",
            level: 3,
            order_index: 8,
          },
          {
            name: "Payroll",
            icon: "payroll",
            path: "/master/hr/payroll",
            level: 3,
            order_index: 9,
          },
        ],
      },
      {
        name: "PPIC",
        icon: "ppic",
        path: null,
        level: 2,
        order_index: 4,
        children: [
          {
            name: "Schedule",
            icon: "schedule",
            path: "/master/ppic/schedule",
            level: 3,
            order_index: 1,
          },
          {
            name: "Fleet Capacity",
            icon: "capacity",
            path: "/master/ppic/fleet-capacity",
            level: 3,
            order_index: 2,
          },
        ],
      },
      {
        name: "Production",
        icon: "production",
        path: null,
        level: 2,
        order_index: 5,
        children: [
          {
            name: "Kategori Kendala",
            icon: "schedule",
            path: "/master/produksi/kategori-kendala",
            level: 3,
            order_index: 1,
          },
          {
            name: "Kriteria Kendala",
            icon: "capacity",
            path: "/master/produksi/kriteria-kendala",
            level: 3,
            order_index: 2,
          },
          {
            name: "Kode Produksi",
            icon: "schedule",
            path: "/master/produksi/kode-produksi",
            level: 3,
            order_index: 3,
          },
        ],
      },
      {
        name: "Marketing",
        icon: "marketing",
        path: null,
        level: 2,
        order_index: 6,
        children: [
          {
            name: "Marketing",
            icon: "marketing",
            path: "/master/marketing/marketing",
            level: 3,
            order_index: 1,
          },
          {
            name: "Customer",
            icon: "customer",
            path: "/master/marketing/customer",
            level: 3,
            order_index: 2,
          },
          {
            name: "Brand",
            icon: "brand",
            path: "/master/marketing/brand",
            level: 3,
            order_index: 3,
          },
          {
            name: "Delivery",
            icon: "delivery",
            path: "/master/marketing/delivery",
            level: 3,
            order_index: 4,
          },
          {
            name: "Product",
            icon: "product",
            path: "/master/marketing/product",
            level: 3,
            order_index: 5,
          },
          {
            name: "Unit",
            icon: "unit",
            path: "/master/marketing/unit",
            level: 3,
            order_index: 6,
          },
          {
            name: "Item",
            icon: "item",
            path: "/master/marketing/item",
            level: 3,
            order_index: 7,
          },
          {
            name: "Machine Stage",
            icon: "machine",
            path: "/master/marketing/machine-stage",
            level: 3,
            order_index: 8,
          },
          {
            name: "Stage",
            icon: "stage",
            path: "/master/marketing/stage",
            level: 3,
            order_index: 9,
          },
          {
            name: "Stage Machine",
            icon: "machine",
            path: "/master/marketing/stage-machine",
            level: 3,
            order_index: 10,
          },
        ],
      },
      {
        name: "General",
        icon: "general",
        path: null,
        level: 2,
        order_index: 7,
        children: [
          {
            name: "Access",
            icon: "access",
            path: "/master/access",
            level: 3,
            order_index: 1,
          },
          {
            name: "User",
            icon: "user",
            path: "/master/user",
            level: 3,
            order_index: 2,
          },
        ],
      },
    ],
  },
];

async function seedMenus() {
  try {
    console.log("Starting menu seeding...");
    // Truncate existing menus
    //await MasterMenu.destroy({ where: {}, truncate: true, cascade: true });

    for (const parentMenu of menuData) {
      // Create parent menu (Level 1)
      const parent = await MasterMenu.create({
        name: parentMenu.name,
        icon: parentMenu.icon,
        path: parentMenu.path,
        level: parentMenu.level,
        order_index: parentMenu.order_index,
        parent_id: null,
      });

      console.log(`✓ Created parent menu: ${parent.name}`);

      // Create child menus (Level 2)
      if (parentMenu.children) {
        for (const childMenu of parentMenu.children) {
          const child = await MasterMenu.create({
            name: childMenu.name,
            icon: childMenu.icon,
            path: childMenu.path,
            level: childMenu.level,
            order_index: childMenu.order_index,
            parent_id: parent.id,
          });

          console.log(`  ✓ Created child menu: ${child.name}`);

          // Create grandchild menus (Level 3)
          if (childMenu.children) {
            for (const grandchildMenu of childMenu.children) {
              const grandchild = await MasterMenu.create({
                name: grandchildMenu.name,
                icon: grandchildMenu.icon,
                path: grandchildMenu.path,
                level: grandchildMenu.level,
                order_index: grandchildMenu.order_index,
                parent_id: child.id,
              });

              console.log(`    ✓ Created grandchild menu: ${grandchild.name}`);
            }
          }
        }
      }
    }

    console.log("\n✅ All menus seeded successfully!");
  } catch (error) {
    console.error("❌ Error seeding menus:", error);
    throw error;
  }
}
// Run seeder if executed directly
if (require.main === module) {
  seedMenus()
    .then(() => {
      console.log("Seeding completed");
      process.exit(0);
    })
    .catch((error) => {
      console.error("Seeding failed:", error);
      process.exit(1);
    });
}
module.exports = seedMenus;
